### ISSUE TITLE
How does building this module work?

### ISSUE THREAD

**Issue by alexdrans** [michaellyons/react-amazon-gallery#1]
Hi,

Nice module, thanks!

I needed to fork it today, and I'm a bit confused as to how build works? /lib is ignored by git, and when I install from github, no build happens, so /lib/index.js references non-existent files (the components). What is the correct way to build?

**Comment by michaellyons** [comment]
Hey sorry for the slow reply,

I implemented an entirely different development environment, and lib is not ignored by git anymore.

You should be able to pull and rebase the updated master. I'll put development and build instructions in the README momentarily. 

To build in this version you'll want to run ```npm run babel``` to transpile the src code and for development you can just run ```npm start``` which will have webpack watch the src files and host a demo app on localhost:8000
